all: 
	convert -resize '25%%' trump-xp-4-big.png trump-xp-4.png
	convert -resize '25%%' ec-3-banner-big.png ec-3-banner.png
	convert -resize '25%%' ec-3-banner-j-big.png ec-3-banner-j.png
	convert 9-11-13.png     -background transparent -gravity center -extent 2000x1114 9-11-13-pad.png
	convert reliability-3.png -background transparent -gravity center -extent 2000x870  reliability-3-pad.png
