all: 
	convert -resize '25%%' ec-1-banner-big.png ec-1-banner.png
	convert y-5-6x.png -background transparent -gravity center -extent 2000x690 y-5-6x-pad.png
	convert y-1-2x-3x2-4x3.png -background transparent -gravity center -extent 2000x968 y-1-2x-3x2-4x3-pad.png
